name: Simple Workflow

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the job
jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run a simple shell command
      - name: Say Hello World
        run: echo "Hello, World!"

